services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: stockmarket
      RABBITMQ_DEFAULT_PASS: supersecret123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  stock-publisher:
    image: justin799/stock-publisher
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://stockmarket:supersecret123@rabbitmq:5672/
  mongo1:
    image: mongo:7.0
    ports:
      - 27017:27017
    container_name: mongo1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongo1-data:/data/db
      - mongo1-config:/data/configdb
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'try { rs.status() } catch (err) { rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"host.docker.internal:27017\",priority:1},{_id:1,host:\"host.docker.internal:27018\",priority:0.5},{_id:2,host:\"host.docker.internal:27019\",priority:0.5}]}) }' | mongosh --port 27017 --quiet"]
      interval: 10s
      retries: 5
  mongo2:
    image: mongo:7.0
    ports:
      - 27018:27018
    container_name: mongo2
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongo2-data:/data/db
      - mongo2-config:/data/configdb
  mongo3:
    image: mongo:7.0
    ports:
      - 27019:27019
    container_name: mongo3
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongo3-data:/data/db
      - mongo3-config:/data/configdb
  consumer-aapl:
    image: justin799/consumer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: stockmarket
      RABBITMQ_PASS: supersecret123
      RABBITMQ_QUEUE: AAPL
      MONGODB_URI: mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/?replicaSet=rs0
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "mongosh 'mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/?replicaSet=rs0' --eval 'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  consumer-msft:
    image: justin799/consumer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: stockmarket
      RABBITMQ_PASS: supersecret123
      RABBITMQ_QUEUE: MSFT
      MONGODB_URI: mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/?replicaSet=rs0
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "mongosh 'mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/?replicaSet=rs0' --eval 'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  consumer-tsla:
    image: justin799/consumer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: stockmarket
      RABBITMQ_PASS: supersecret123
      RABBITMQ_QUEUE: TSLA
      MONGODB_URI: mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/?replicaSet=rs0
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "mongosh 'mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/?replicaSet=rs0' --eval 'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  stock-liveview:
    image: justin799/stock-liveview
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "mongosh 'mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/?replicaSet=rs0' --eval 'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      MONGODB_URL: mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/?replicaSet=rs0
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks

volumes:
  mongo1-data:
  mongo1-config:
  mongo2-data:
  mongo2-config:
  mongo3-data:
  mongo3-config: